//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khaled.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Khaled.Resources.AppResources.de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzeptieren.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKTIONEN.
        /// </summary>
        internal static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  عربي .
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botschaften &amp; Behörden.
        /// </summary>
        internal static string AuthoritiesAndEmbassies {
            get {
                return ResourceManager.GetString("AuthoritiesAndEmbassies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zurück.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty &amp; Wellness.
        /// </summary>
        internal static string BeautyAndWellness {
            get {
                return ResourceManager.GetString("BeautyAndWellness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berlin.
        /// </summary>
        internal static string Berlin {
            get {
                return ResourceManager.GetString("Berlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMIN BUCHEN.
        /// </summary>
        internal static string BOOKSLOT {
            get {
                return ResourceManager.GetString("BOOKSLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autos.
        /// </summary>
        internal static string CarWorksShop {
            get {
                return ResourceManager.GetString("CarWorksShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändere die Sprache.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Stadt.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demnächst.
        /// </summary>
        internal static string CommingSoon {
            get {
                return ResourceManager.GetString("CommingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handwerk &amp; Reparatur Service.
        /// </summary>
        internal static string ConstructionAndRepair {
            get {
                return ResourceManager.GetString("ConstructionAndRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kultur &amp; Kunst.
        /// </summary>
        internal static string CultureAndArt {
            get {
                return ResourceManager.GetString("CultureAndArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Täglicher Bedarf.
        /// </summary>
        internal static string DailyShopping {
            get {
                return ResourceManager.GetString("DailyShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BESCHREIBUNG.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir konnten hier leider nichts finden. Probiere eine andere Stadt oder erweitere deinen Suchradius..
        /// </summary>
        internal static string DidntFindAnything {
            get {
                return ResourceManager.GetString("DidntFindAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutz.
        /// </summary>
        internal static string DSGVO {
            get {
                return ResourceManager.GetString("DSGVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildung &amp; Schulen.
        /// </summary>
        internal static string EducationalInstitutions {
            get {
                return ResourceManager.GetString("EducationalInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notfälle.
        /// </summary>
        internal static string Emergencies {
            get {
                return ResourceManager.GetString("Emergencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essen &amp; Trinken.
        /// </summary>
        internal static string FoodAndDrink {
            get {
                return ResourceManager.GetString("FoodAndDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutschland.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sie haben die Standortanforderung bereits abgelehnt, bitte aktivieren Sie sie wieder in den Einstellungen Ihres Geräts.
        /// </summary>
        internal static string GpsDenied {
            get {
                return ResourceManager.GetString("GpsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamburg.
        /// </summary>
        internal static string Hamburg {
            get {
                return ResourceManager.GetString("Hamburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partys &amp; Events.
        /// </summary>
        internal static string HappeningsAndEvents {
            get {
                return ResourceManager.GetString("HappeningsAndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesundheit.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesundheit &amp; Medizin.
        /// </summary>
        internal static string HealthAndMed {
            get {
                return ResourceManager.GetString("HealthAndMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobby &amp; Freizeit.
        /// </summary>
        internal static string HobbyAndAmusement {
            get {
                return ResourceManager.GetString("HobbyAndAmusement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels &amp; Unterkünfte.
        /// </summary>
        internal static string HotelsAndProperties {
            get {
                return ResourceManager.GetString("HotelsAndProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum &amp; Kontakt.
        /// </summary>
        internal static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KATEGORIEN.
        /// </summary>
        internal static string KATEGORIES {
            get {
                return ResourceManager.GetString("KATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recht &amp; Finanzen.
        /// </summary>
        internal static string LawAndFinance {
            get {
                return ResourceManager.GetString("LawAndFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptmenü.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to München.
        /// </summary>
        internal static string Munich {
            get {
                return ResourceManager.GetString("Munich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Position.
        /// </summary>
        internal static string MyPosition {
            get {
                return ResourceManager.GetString("MyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächstes.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momentan sind leider keine Angebote in deiner Region vorhanden. Dies wird sich bald ändern!.
        /// </summary>
        internal static string NoOffers {
            get {
                return ResourceManager.GetString("NoOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANGEBOTE.
        /// </summary>
        internal static string OFFERS {
            get {
                return ResourceManager.GetString("OFFERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oder.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmen &amp; Vereine.
        /// </summary>
        internal static string OrganizationsAndAssociations {
            get {
                return ResourceManager.GetString("OrganizationsAndAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle eine Kategorie aus.
        /// </summary>
        internal static string PickACategory {
            get {
                return ResourceManager.GetString("PickACategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle einen Ort aus.
        /// </summary>
        internal static string PickArea {
            get {
                return ResourceManager.GetString("PickArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wähle eine Unterkategorie aus.
        /// </summary>
        internal static string PickASubCat {
            get {
                return ResourceManager.GetString("PickASubCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle eine Stadt aus.
        /// </summary>
        internal static string PickFromCity {
            get {
                return ResourceManager.GetString("PickFromCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle eine Sprache aus:.
        /// </summary>
        internal static string PickLanguage {
            get {
                return ResourceManager.GetString("PickLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gps nicht erlaubt. Bitte installiere die App neu, wenn du deine Meinung geändert hast..
        /// </summary>
        internal static string PleaseAllowGPS {
            get {
                return ResourceManager.GetString("PleaseAllowGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religiöse Einrichtungen.
        /// </summary>
        internal static string ReligiousInstitions {
            get {
                return ResourceManager.GetString("ReligiousInstitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immobilien mieten &amp; kaufen.
        /// </summary>
        internal static string RentAndBuyRealEstate {
            get {
                return ResourceManager.GetString("RentAndBuyRealEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche innerhalb dieser Kategorie.
        /// </summary>
        internal static string SearchInCat {
            get {
                return ResourceManager.GetString("SearchInCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das hab ich bei  Waynou gesehen: .
        /// </summary>
        internal static string SharingText {
            get {
                return ResourceManager.GetString("SharingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interessante Orte .
        /// </summary>
        internal static string SightAndExcursion {
            get {
                return ResourceManager.GetString("SightAndExcursion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuttgart.
        /// </summary>
        internal static string Stuttgart {
            get {
                return ResourceManager.GetString("Stuttgart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwende meinen Standort.
        /// </summary>
        internal static string TakeMyGpsLocation {
            get {
                return ResourceManager.GetString("TakeMyGpsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedingungen  &amp; Konditionen.
        /// </summary>
        internal static string TermsAndCon {
            get {
                return ResourceManager.GetString("TermsAndCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzungsbedingungen.
        /// </summary>
        internal static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP KATEGORIEN.
        /// </summary>
        internal static string TOPCATS {
            get {
                return ResourceManager.GetString("TOPCATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reise  &amp; Tourismus.
        /// </summary>
        internal static string TravelAndToursim {
            get {
                return ResourceManager.GetString("TravelAndToursim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wonach suchst du?.
        /// </summary>
        internal static string WhatAreYouLookingFor {
            get {
                return ResourceManager.GetString("WhatAreYouLookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to innerhalb.
        /// </summary>
        internal static string Within {
            get {
                return ResourceManager.GetString("Within", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist hier:.
        /// </summary>
        internal static string YouAreHere {
            get {
                return ResourceManager.GetString("YouAreHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein aktueller Standort.
        /// </summary>
        internal static string YouCurrentLocation {
            get {
                return ResourceManager.GetString("YouCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Standort.
        /// </summary>
        internal static string YourGpsLocation {
            get {
                return ResourceManager.GetString("YourGpsLocation", resourceCulture);
            }
        }
    }
}
