//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khaled.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Khaled.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abort.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIONS.
        /// </summary>
        internal static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities &amp; embassies.
        /// </summary>
        internal static string AuthoritiesAndEmbassies {
            get {
                return ResourceManager.GetString("AuthoritiesAndEmbassies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty &amp; Wellness.
        /// </summary>
        internal static string BeautyAndWellness {
            get {
                return ResourceManager.GetString("BeautyAndWellness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berlin.
        /// </summary>
        internal static string Berlin {
            get {
                return ResourceManager.GetString("Berlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK SLOT.
        /// </summary>
        internal static string BOOKSLOT {
            get {
                return ResourceManager.GetString("BOOKSLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garages &amp; experts.
        /// </summary>
        internal static string CarWorksShop {
            get {
                return ResourceManager.GetString("CarWorksShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your city.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comming soon.
        /// </summary>
        internal static string CommingSoon {
            get {
                return ResourceManager.GetString("CommingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction &amp; repair service.
        /// </summary>
        internal static string ConstructionAndRepair {
            get {
                return ResourceManager.GetString("ConstructionAndRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture &amp; art.
        /// </summary>
        internal static string CultureAndArt {
            get {
                return ResourceManager.GetString("CultureAndArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily shopping.
        /// </summary>
        internal static string DailyShopping {
            get {
                return ResourceManager.GetString("DailyShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldnt find anything here. Try a different city or widen your radius..
        /// </summary>
        internal static string DidntFindAnything {
            get {
                return ResourceManager.GetString("DidntFindAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data privacy.
        /// </summary>
        internal static string DSGVO {
            get {
                return ResourceManager.GetString("DSGVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational institutions.
        /// </summary>
        internal static string EducationalInstitutions {
            get {
                return ResourceManager.GetString("EducationalInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergencies.
        /// </summary>
        internal static string Emergencies {
            get {
                return ResourceManager.GetString("Emergencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food &amp; drinks.
        /// </summary>
        internal static string FoodAndDrink {
            get {
                return ResourceManager.GetString("FoodAndDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You already denied the location request, please enable it back in your devices settings.
        /// </summary>
        internal static string GpsDenied {
            get {
                return ResourceManager.GetString("GpsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamburg.
        /// </summary>
        internal static string Hamburg {
            get {
                return ResourceManager.GetString("Hamburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happenings &amp; events.
        /// </summary>
        internal static string HappeningsAndEvents {
            get {
                return ResourceManager.GetString("HappeningsAndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health &amp; medicine.
        /// </summary>
        internal static string HealthAndMed {
            get {
                return ResourceManager.GetString("HealthAndMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobby &amp; amusement.
        /// </summary>
        internal static string HobbyAndAmusement {
            get {
                return ResourceManager.GetString("HobbyAndAmusement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels &amp; properties.
        /// </summary>
        internal static string HotelsAndProperties {
            get {
                return ResourceManager.GetString("HotelsAndProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint &amp; Contact.
        /// </summary>
        internal static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        internal static string KATEGORIES {
            get {
                return ResourceManager.GetString("KATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law &amp; finance.
        /// </summary>
        internal static string LawAndFinance {
            get {
                return ResourceManager.GetString("LawAndFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munich.
        /// </summary>
        internal static string Munich {
            get {
                return ResourceManager.GetString("Munich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My position.
        /// </summary>
        internal static string MyPosition {
            get {
                return ResourceManager.GetString("MyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, we do not have any offers in your region yet. This will certainly change soon!.
        /// </summary>
        internal static string NoOffers {
            get {
                return ResourceManager.GetString("NoOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFERS.
        /// </summary>
        internal static string OFFERS {
            get {
                return ResourceManager.GetString("OFFERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations &amp; Associations.
        /// </summary>
        internal static string OrganizationsAndAssociations {
            get {
                return ResourceManager.GetString("OrganizationsAndAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Category.
        /// </summary>
        internal static string PickACategory {
            get {
                return ResourceManager.GetString("PickACategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick area.
        /// </summary>
        internal static string PickArea {
            get {
                return ResourceManager.GetString("PickArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Subcategory.
        /// </summary>
        internal static string PickASubCat {
            get {
                return ResourceManager.GetString("PickASubCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from a city.
        /// </summary>
        internal static string PickFromCity {
            get {
                return ResourceManager.GetString("PickFromCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your language:.
        /// </summary>
        internal static string PickLanguage {
            get {
                return ResourceManager.GetString("PickLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gps not allowed. Please reinstall the app, if you changed your mind..
        /// </summary>
        internal static string PleaseAllowGPS {
            get {
                return ResourceManager.GetString("PleaseAllowGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radius.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religious institutions.
        /// </summary>
        internal static string ReligiousInstitions {
            get {
                return ResourceManager.GetString("ReligiousInstitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent &amp; buy real estate.
        /// </summary>
        internal static string RentAndBuyRealEstate {
            get {
                return ResourceManager.GetString("RentAndBuyRealEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search inside this category.
        /// </summary>
        internal static string SearchInCat {
            get {
                return ResourceManager.GetString("SearchInCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out what I found on Waynou: .
        /// </summary>
        internal static string SharingText {
            get {
                return ResourceManager.GetString("SharingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        internal static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sights &amp; excursions.
        /// </summary>
        internal static string SightAndExcursion {
            get {
                return ResourceManager.GetString("SightAndExcursion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuttgart.
        /// </summary>
        internal static string Stuttgart {
            get {
                return ResourceManager.GetString("Stuttgart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my gps location.
        /// </summary>
        internal static string TakeMyGpsLocation {
            get {
                return ResourceManager.GetString("TakeMyGpsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TermsAndCon {
            get {
                return ResourceManager.GetString("TermsAndCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        internal static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP CATEGORIES.
        /// </summary>
        internal static string TOPCATS {
            get {
                return ResourceManager.GetString("TOPCATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel &amp; tourism.
        /// </summary>
        internal static string TravelAndToursim {
            get {
                return ResourceManager.GetString("TravelAndToursim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you looking for?.
        /// </summary>
        internal static string WhatAreYouLookingFor {
            get {
                return ResourceManager.GetString("WhatAreYouLookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to within.
        /// </summary>
        internal static string Within {
            get {
                return ResourceManager.GetString("Within", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here:.
        /// </summary>
        internal static string YouAreHere {
            get {
                return ResourceManager.GetString("YouAreHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your gps location.
        /// </summary>
        internal static string YouCurrentLocation {
            get {
                return ResourceManager.GetString("YouCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your GPS location.
        /// </summary>
        internal static string YourGpsLocation {
            get {
                return ResourceManager.GetString("YourGpsLocation", resourceCulture);
            }
        }
    }
}
