//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khaled.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Khaled.Resources.AppResources.ar", typeof(AppResources_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجراءات.
        /// </summary>
        internal static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارات و دوائر رسمية .
        /// </summary>
        internal static string AuthoritiesAndEmbassies {
            get {
                return ResourceManager.GetString("AuthoritiesAndEmbassies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناية وجمال.
        /// </summary>
        internal static string BeautyAndWellness {
            get {
                return ResourceManager.GetString("BeautyAndWellness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برلين.
        /// </summary>
        internal static string Berlin {
            get {
                return ResourceManager.GetString("Berlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحجز موعد.
        /// </summary>
        internal static string BOOKSLOT {
            get {
                return ResourceManager.GetString("BOOKSLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عالم السيارات.
        /// </summary>
        internal static string CarWorksShop {
            get {
                return ResourceManager.GetString("CarWorksShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر لغة.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدينتك.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آتي قريباً.
        /// </summary>
        internal static string CommingSoon {
            get {
                return ResourceManager.GetString("CommingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعمال بناء وصيانة.
        /// </summary>
        internal static string ConstructionAndRepair {
            get {
                return ResourceManager.GetString("ConstructionAndRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثقافة وفن.
        /// </summary>
        internal static string CultureAndArt {
            get {
                return ResourceManager.GetString("CultureAndArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحتياجات اليومية.
        /// </summary>
        internal static string DailyShopping {
            get {
                return ResourceManager.GetString("DailyShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لم نتمكن من العثور على أي شيء هنا. جرب مدينة مختلفة أو وسّع قطر البحث .
        /// </summary>
        internal static string DidntFindAnything {
            get {
                return ResourceManager.GetString("DidntFindAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة الخصوصية.
        /// </summary>
        internal static string DSGVO {
            get {
                return ResourceManager.GetString("DSGVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تدريب و تعليم.
        /// </summary>
        internal static string EducationalInstitutions {
            get {
                return ResourceManager.GetString("EducationalInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالات طوارئ.
        /// </summary>
        internal static string Emergencies {
            get {
                return ResourceManager.GetString("Emergencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطاعم و مقاهي.
        /// </summary>
        internal static string FoodAndDrink {
            get {
                return ResourceManager.GetString("FoodAndDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ألمانيا.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذهب.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لقد رفضت طلب الموقع. يرجى تمكينه مرة أخرى في إعدادات جهازك.
        /// </summary>
        internal static string GpsDenied {
            get {
                return ResourceManager.GetString("GpsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هامبورغ.
        /// </summary>
        internal static string Hamburg {
            get {
                return ResourceManager.GetString("Hamburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعاليات وحفلات .
        /// </summary>
        internal static string HappeningsAndEvents {
            get {
                return ResourceManager.GetString("HappeningsAndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صحة.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صحة وطب.
        /// </summary>
        internal static string HealthAndMed {
            get {
                return ResourceManager.GetString("HealthAndMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هواية وترفيه.
        /// </summary>
        internal static string HobbyAndAmusement {
            get {
                return ResourceManager.GetString("HobbyAndAmusement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فنادق وشقق مفروشة.
        /// </summary>
        internal static string HotelsAndProperties {
            get {
                return ResourceManager.GetString("HotelsAndProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        internal static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وظائف.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئات.
        /// </summary>
        internal static string KATEGORIES {
            get {
                return ResourceManager.GetString("KATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلم.
        /// </summary>
        internal static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستشارت قانونية و مالية.
        /// </summary>
        internal static string LawAndFinance {
            get {
                return ResourceManager.GetString("LawAndFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة الرئيسيّة.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميونخ.
        /// </summary>
        internal static string Munich {
            get {
                return ResourceManager.GetString("Munich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعي.
        /// </summary>
        internal static string MyPosition {
            get {
                return ResourceManager.GetString("MyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لا يوجد  عروض حالياً. ترقّبوا المزيد قريباً.
        /// </summary>
        internal static string NoOffers {
            get {
                return ResourceManager.GetString("NoOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عروض.
        /// </summary>
        internal static string OFFERS {
            get {
                return ResourceManager.GetString("OFFERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أو.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منظمات وجمعيات.
        /// </summary>
        internal static string OrganizationsAndAssociations {
            get {
                return ResourceManager.GetString("OrganizationsAndAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر فئة.
        /// </summary>
        internal static string PickACategory {
            get {
                return ResourceManager.GetString("PickACategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر منطقة .
        /// </summary>
        internal static string PickArea {
            get {
                return ResourceManager.GetString("PickArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر فئة فرعية.
        /// </summary>
        internal static string PickASubCat {
            get {
                return ResourceManager.GetString("PickASubCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر مدينة.
        /// </summary>
        internal static string PickFromCity {
            get {
                return ResourceManager.GetString("PickFromCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر لغة:.
        /// </summary>
        internal static string PickLanguage {
            get {
                return ResourceManager.GetString("PickLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نظام تحديد المواقع العالمي غير مسموح به، يرجى إعادة تثبيت التطبيق، إذا غيرت رأيك .
        /// </summary>
        internal static string PleaseAllowGPS {
            get {
                return ResourceManager.GetString("PleaseAllowGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطر البحث.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  مراكز دينية و عبادة.
        /// </summary>
        internal static string ReligiousInstitions {
            get {
                return ResourceManager.GetString("ReligiousInstitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  عقارات للبيع و الإيجار.
        /// </summary>
        internal static string RentAndBuyRealEstate {
            get {
                return ResourceManager.GetString("RentAndBuyRealEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إبحث في هذه الفئة.
        /// </summary>
        internal static string SearchInCat {
            get {
                return ResourceManager.GetString("SearchInCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  : Waynou شاهد ماذا وجدت على تطبيق .
        /// </summary>
        internal static string SharingText {
            get {
                return ResourceManager.GetString("SharingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسوق.
        /// </summary>
        internal static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معالم سياحية ورحلات.
        /// </summary>
        internal static string SightAndExcursion {
            get {
                return ResourceManager.GetString("SightAndExcursion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شتوتغارت.
        /// </summary>
        internal static string Stuttgart {
            get {
                return ResourceManager.GetString("Stuttgart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الخاص بي GPS إستخدام موقع ال .
        /// </summary>
        internal static string TakeMyGpsLocation {
            get {
                return ResourceManager.GetString("TakeMyGpsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحكام والشروط.
        /// </summary>
        internal static string TermsAndCon {
            get {
                return ResourceManager.GetString("TermsAndCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط الإستخدام.
        /// </summary>
        internal static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئات مهمة.
        /// </summary>
        internal static string TOPCATS {
            get {
                return ResourceManager.GetString("TOPCATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياحة وسفر.
        /// </summary>
        internal static string TravelAndToursim {
            get {
                return ResourceManager.GetString("TravelAndToursim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن ماذا تبحث؟.
        /// </summary>
        internal static string WhatAreYouLookingFor {
            get {
                return ResourceManager.GetString("WhatAreYouLookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضمن.
        /// </summary>
        internal static string Within {
            get {
                return ResourceManager.GetString("Within", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنت هنا:.
        /// </summary>
        internal static string YouAreHere {
            get {
                return ResourceManager.GetString("YouAreHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع الخاص بك.
        /// </summary>
        internal static string YouCurrentLocation {
            get {
                return ResourceManager.GetString("YouCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الخاص بك GPS موقع .
        /// </summary>
        internal static string YourGpsLocation {
            get {
                return ResourceManager.GetString("YourGpsLocation", resourceCulture);
            }
        }
    }
}
